# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
dimens_1 = np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
dimens_2 = np.array([[1,2,3,4,5],
                    [6,7,8,9,10]])

# Create a 3-dimensional Numpy array using np.array()
dimens_3 = np.array([[[1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15]],
                    [[1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [8]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
dimens_1.shape, dimens_1.ndim, dimens_1.dtype, dimens_1.size, type(dimens_1)

((5,), 1, dtype('int32'), 5, numpy.ndarray)

In [9]:
# Attributes of 2-dimensional array
dimens_2.shape, dimens_2.ndim, dimens_2.dtype, dimens_2.size, type(dimens_2)

((2, 5), 2, dtype('int32'), 10, numpy.ndarray)

In [10]:
# Attributes of 3-dimensional array
dimens_3.shape, dimens_3.ndim, dimens_3.dtype, dimens_3.size, type(dimens_3)

((2, 3, 5), 3, dtype('int32'), 30, numpy.ndarray)

In [12]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(dimens_2)
df

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [14]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size=(7, 2))
random_array

array([[7, 0],
       [1, 4],
       [6, 7],
       [4, 3],
       [9, 3],
       [0, 2],
       [7, 5]])

In [21]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_floats = np.random.random((3,5))
random_array_floats

array([[0.77168086, 0.01074346, 0.1052006 , 0.69394434, 0.19405758],
       [0.27581612, 0.20256546, 0.58126742, 0.68541659, 0.8087644 ],
       [0.70287731, 0.15011438, 0.73796723, 0.19702924, 0.24661869]])

In [22]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_seed = np.random.randint(0, 10, size=(4,6))
random_array_seed

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [23]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_saved = np.random.randint(1, 10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(random_array_saved)

array([1, 2, 3, 4, 5, 7, 9])

In [24]:
# Find the 0'th index of the latest array you created
random_array_saved[0]

array([9, 1, 3, 7, 4, 9, 3])

In [26]:
# Get the first 2 rows of latest array you created
random_array_saved[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [36]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_saved[:2, :1]

array([[9],
       [5]])

In [39]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
new_random_array = np.random.randint(0, 10, size=(3,5))
print(new_random_array)

new_ones_array = np.ones((3,5))
print(new_ones_array)

[[0 8 6 8 7]
 [0 7 7 2 0]
 [7 2 2 0 4]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
# Add the two arrays together
new_random_array + new_ones_array

array([[1., 9., 7., 9., 8.],
       [1., 8., 8., 3., 1.],
       [8., 3., 3., 1., 5.]])

In [41]:
# Create another array of ones of shape (5, 3)
third_ones_array = np.ones((5,3))
third_ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
# Try add the array of ones and the other most recent array together
third_ones_array + new_random_array

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [43]:
# Create another array of ones of shape (3, 5)
fourth_ones_array = np.ones((3,5))
fourth_ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
# Subtract the new array of ones from the other most recent array
new_random_array - fourth_ones_array

array([[-1.,  7.,  5.,  7.,  6.],
       [-1.,  6.,  6.,  1., -1.],
       [ 6.,  1.,  1., -1.,  3.]])

In [46]:
# Multiply the ones array with the latest array
fourth_ones_array * new_random_array

array([[0., 8., 6., 8., 7.],
       [0., 7., 7., 2., 0.],
       [7., 2., 2., 0., 4.]])

In [47]:
# Take the latest array to the power of 2 using '**'
new_random_array**2

array([[ 0, 64, 36, 64, 49],
       [ 0, 49, 49,  4,  0],
       [49,  4,  4,  0, 16]])

In [48]:
# Do the same thing with np.square()
np.square(new_random_array)

array([[ 0, 64, 36, 64, 49],
       [ 0, 49, 49,  4,  0],
       [49,  4,  4,  0, 16]])

In [49]:
# Find the mean of the latest array using np.mean()
np.mean(new_random_array)

4.0

In [50]:
# Find the maximum of the latest array using np.max()
np.max(new_random_array)

8

In [51]:
# Find the minimum of the latest array using np.min()
np.min(new_random_array)

0

In [54]:
# Find the standard deviation of the latest array
np.std(new_random_array)

3.141125063837266

In [55]:
# Find the variance of the latest array
np.var(new_random_array)

9.866666666666667

In [56]:
# Reshape the latest array to (3, 5, 1)
new_random_array.reshape(3,5,1)

array([[[0],
        [8],
        [6],
        [8],
        [7]],

       [[0],
        [7],
        [7],
        [2],
        [0]],

       [[7],
        [2],
        [2],
        [0],
        [4]]])

In [57]:
# Transpose the latest array
new_random_array.T

array([[0, 0, 7],
       [8, 7, 2],
       [6, 7, 2],
       [8, 2, 0],
       [7, 0, 4]])

What does the transpose do?

In [58]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
newest_random_arrays_1 = np.random.randint(0, 10, size=(3,3))
newest_random_arrays_2 = np.random.randint(0, 10, size=(3,2))

In [59]:
# Perform a dot product on the two newest arrays you created
newest_random_arrays_1 * newest_random_arrays_2

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [60]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
newest_random_arrays_3 = np.random.randint(0, 10, size=(4,3))
newest_random_arrays_4 = np.random.randint(0, 10, size=(4,3))

In [61]:
# Perform a dot product on the two newest arrays you created
newest_random_arrays_3 * newest_random_arrays_4

array([[45, 18,  0],
       [12,  0,  6],
       [ 0, 16, 54],
       [36, 18, 48]])

It doesn't work. How would you fix it?

In [62]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
newest_random_arrays_3.T, newest_random_arrays_4.T

(array([[5, 2, 0, 6],
        [2, 4, 4, 6],
        [0, 2, 9, 8]]),
 array([[9, 6, 3, 6],
        [9, 0, 4, 3],
        [2, 3, 6, 6]]))

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [63]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
newest_random_arrays_5 = np.random.randint(0, 10, size=(4,4))
newest_random_arrays_6 = np.random.randint(0, 10, size=(4,4))

In [64]:
# Compare the two arrays with '>'
newest_random_arrays_5 > newest_random_arrays_6

array([[False, False, False,  True],
       [ True, False, False, False],
       [ True,  True, False, False],
       [False, False, False,  True]])

What happens when you compare the arrays with `>`?

In [65]:
# Compare the two arrays with '>='
newest_random_arrays_5 >= newest_random_arrays_6

array([[False, False, False,  True],
       [ True, False, False, False],
       [ True,  True, False, False],
       [False, False,  True,  True]])

In [66]:
# Find which elements of the first array are greater than 7
newest_random_arrays_5 > 7

array([[False, False, False,  True],
       [ True, False, False, False],
       [ True, False,  True, False],
       [False, False,  True,  True]])

In [67]:
# Which parts of each array are equal? (try using '==')
newest_random_arrays_5 == newest_random_arrays_6

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [68]:
# Sort one of the arrays you just created in ascending order
np.sort(newest_random_arrays_5)

array([[1, 2, 5, 9],
       [3, 4, 5, 8],
       [6, 6, 8, 9],
       [0, 0, 8, 8]])

In [69]:
# Sort the indexes of one of the arrays you just created
np.sort(newest_random_arrays_5[0])

array([1, 2, 5, 9])

In [71]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(newest_random_arrays_5)

3

In [72]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(newest_random_arrays_5)

12

In [73]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(newest_random_arrays_5, axis=1)

array([3, 0, 0, 2], dtype=int64)

In [74]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(newest_random_arrays_5, axis=0)

array([3, 3, 0, 1], dtype=int64)

In [76]:
# Create an array of normally distributed random numbers
last_random_array = np.random.randint(0, 10, size=(4,4))
last_random_array

array([[6, 4, 0, 0],
       [2, 1, 4, 9],
       [5, 6, 3, 6],
       [7, 0, 5, 7]])

In [79]:
# Create an array with 10 evenly spaced numbers between 1 and 100
lastest_random_array = np.arange(0, 100, 10)
lastest_random_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.